spring.application.name=Monster-Inn


# Koneksi ke MySQL 
spring.datasource.url=jdbc:mysql://localhost:3306/monster_inn
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Biar Spring Boot otomatis bikin tabel di database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Run data.sql after Hibernate creates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Konfigurasi User Login Default
spring.security.user.name=admin
spring.security.user.password=admin123