spring.application.name=Monster-Inn


# Port dinamis untuk Railway
server.port=${PORT:8080}

# Koneksi ke MySQL (Mendukung Railway dan Localhost)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/monster_inn?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Biar perubahan HTML Thymeleaf langsung keliatan tanpa restart
spring.thymeleaf.cache=false

# Biar Spring Boot otomatis bikin tabel di database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Run data.sql after Hibernate creates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# # Konfigurasi User Login Default
# spring.security.user.name=admin
# spring.security.user.password=admin123
